debate_config: dict = {
    "base_answer": "",
    "base_prompt": "Find the right next action to execute for the following user instruction:\n##instruction##\nand the current state of the computer:\n##gui_representation##",
    "player_meta_prompt": "You are a debater. Hello and welcome to the action selection competition, which will be conducted in a debate format. It's not necessary to fully agree with each other's perspectives, as our objective is to find the correct next action.\nThe debate topic is stated as follows:\n##base_prompt##",
    "moderator_meta_prompt": "You are a moderator. There will be two debaters involved in a debate. They will present their answers and discuss their perspectives on the following topic: \"##base_prompt##\"\nAt the end of each round, you will evaluate answers and decide which is correct.",
    "affirmative_prompt": "You think the correct next action is: ##base_answer_aff##. Restate the next action and provide your reasons.",
    "negative_prompt": "##aff_ans##\n\nYou disagree with my next action.\nYou think the correct next action is: ##base_answer_neg##. Provide your next action and reasons.",
    "moderator_prompt": "Now the ##round## round of debate for both sides has ended.\n\nAffirmative side arguing:\n##aff_ans##\n\nNegative side arguing: ##neg_ans##\n\nYou, as the moderator, will evaluate both sides' next actions and determine if there is a clear preference for a next action candidate. If so, please summarize your reasons for supporting affirmative/negative side and give the final next action that you think is correct, and the debate will conclude. If not, the debate will continue to the next round. Now please output your answer in json format, with the format as follows: {\"Whether there is a preference\": \"Yes or No\", \"Supported Side\": \"Affirmative or Negative\", \"Reason\": \"\", \"debate_answer\": \"\"}. Please strictly output in JSON format, do not output irrelevant content.",
    "judge_prompt_last1": "Affirmative side arguing: ##aff_ans##\n\nNegative side arguing: ##neg_ans##\n\nNow, what next action candidates do we have? Present them without reasons.",
    "judge_prompt_last2": "Therefore, ##base_prompt##\nPlease summarize your reasons and give the final answer that you think is correct. Now please output your answer in json format, with the format as follows: {\"Reason\": \"\", \"debate_answer\": \"\"}. Please strictly output in JSON format, do not output irrelevant content. The debate answer should be in the form of an instruction.",
    "debate_prompt": "##oppo_ans##\n\nDo you agree with my perspective? Please provide your reasons and next action."
}