name: crawler
env:
  DESTINATION: 'Chatbot'

# Controls when the workflow will run
on: [push, workflow_dispatch]
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Show where is triggered from
        run: |
          echo a2c2 crawler pipeline is triggered.

  build:
    needs:
      - pre
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' #Python version 3.11 installed
      - name: Install dependencies
        run: |
          ls -la
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Install Google Chrome
      #   run: |
      #     wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      #     echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
      #     sudo apt-get update
      #     sudo apt-get install -y google-chrome-stable
      - name: Download ChromeDriver
        run: |
          # sudo apt-get install xvfb
          # sudo apt-get install unzip
          # CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
          # echo $CHROME_DRIVER_VERSION
          # wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          # sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          # sudo apt-get update 
          # sudo apt install google-chrome-stable

          # wget -N http://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          # unzip chromedriver_linux64.zip
          # chmod +x chromedriver
          # sudo mv -f chromedriver /usr/local/bin/
          sudo apt-get install xvfb
      - name: Run Python script
        run: python crawler.py
        env:
          OXENAI_TOKEN: ${{ secrets.OXENAI_TOKEN }}
